name: Build CV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-cv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Compile CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          latexmk_use_xelatex: true

      - name: Upload CV PDF
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: cv.pdf
